import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/app/components/NavbarComponent';
import 'bootstrap/dist/css/bootstrap.css';

import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap-css-only/css/bootstrap.min.css';
import 'mdbreact/dist/css/mdb.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{marginTop:76}} className={inter.className}>
      <Navbar/>
      {children}</body>
    </html>
  )
}
